[package]
name = "zen-jpeg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zen_jpeg"
path = "src/lib.rs"

[dependencies]
memchr = "2.5.0"
